### ISSUE TITLE
Fails to Download chef-server-core package on Ubuntu 14.04

### ISSUE THREAD

**Issue by SeanSith** [chef-cookbooks/chef-server#73]
When attempting to execute a `kitchen test default-ubuntu-1404`, the VM fails to converge at `apt-get -q -y install chef-server-core=12.0.4-1`. Running the command by hand without "-q" shows that the package fails to download.

**Comment by Angelicvorian** [comment]
I'm getting the same issue, is it perhaps a back package repo? When I run the command manually (sudo apt-get install chef-server-core) I get the following, looks like it's not able to connect to the repo?  It'll sit there at 0% for at least 15mins doing nothing.
I've destroyed the machine and re-created and converged it with the same result.

"vagrant@default-ubuntu-1404:~$ sudo apt-get install chef-server-core
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  chef-server-core
0 upgraded, 1 newly installed, 0 to remove and 91 not upgraded.
Need to get 464 MB of archives.
After this operation, 1,181 MB of additional disk space will be used.
0% [Working]♥vagrant@default-ubuntu-1404:~$ exit
logout
Connection to 127.0.0.1 closed."

**Comment by poma** [comment]
I'm getting `No candidate version available for chef-server-core` error for this package:
```
root@chefserver:~# apt-get update && apt-get install chef-server-core
...
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package chef-server-core
```

Package source is installed correctly so it's probably a problem with repo:
```
root@chefserver:~# cat /etc/apt/sources.list.d/chef_stable_.list
deb https://packagecloud.io/chef/stable/ubuntu trusty main
deb-src https://packagecloud.io/chef/stable/ubuntu trusty main
```

**Comment by jtimberman** [comment]
Hello!

We don't build 32 bit packages for Chef Server, so that's why you're not seeing them in the Package Cloud repository.

The kinds of systems that meet the system requirements for Chef Server are generally 64 bit (16G memory, etc). 

https://docs.chef.io/chef_system_requirements.html

I'm not able to find documentation about the architectures supported for Chef Server, but I'll follow-up internally to make this clear. If you have an absolute need to run Chef Server on a 32 bit machine, you'll need to create your own package.

Thank you for reporting this issue!
